# Generated by Django 5.0.2 on 2025-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
