# Generated by Django 5.0.2 on 2025-07-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
