# Generated by Django 5.0.2 on 2025-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_rejection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_after_verification',
            field=models.BooleanField(default=False),
        ),
    ]
